apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: latest
    environment: dev
    helm.sh/chart: backend-0.1.0
  name: backend-secret
  namespace: dev
stringData:
  database-url: postgresql://postgres:postgres@pg.192.168.49.1.nip.io:5432/users_db
  jwt-secret-key: dev-jwt-secret-key-2026
type: Opaque
