apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: latest
    environment: dev
    helm.sh/chart: backend-0.1.0
  name: backend
  namespace: dev
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
    environment: dev
  type: ClusterIP
