apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-app
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: image-promotion:stg
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployments
spec:
  project: default
  source:
    repoURL: https://github.com/marcellmartini/image-promotion-gitops.git
    targetRevision: env/stg
    path: .  # Branch contém apenas manifests renderizados
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    # Sem automated - sync manual via Kargo argocd-update após promoção
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
