apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: image-promotion
  namespace: image-promotion
spec:
  interval: 5m
  freightCreationPolicy: Automatic
  subscriptions:
    - image:
        repoURL: marcellmartini/image-promotion-backend
        imageSelectionStrategy: NewestBuild
        # Filtra tags que são short commit hashes (8 caracteres hex)
        allowTags: ^[a-f0-9]{8}$
        discoveryLimit: 5
    - image:
        repoURL: marcellmartini/image-promotion-frontend
        imageSelectionStrategy: NewestBuild
        # Filtra tags que são short commit hashes (8 caracteres hex)
        allowTags: ^[a-f0-9]{8}$
        discoveryLimit: 5
